stages:
  - install
  - test
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install_dependencies:
  stage: install
  image: node:latest
  script:
    - npm install
  artifacts:
    when: always
    paths:
      - node_modules/
    expire_in: 1 week

run_tests:
  stage: test
  image: node:latest
  script:
    - ls -la node_modules/@testing-library/jest-dom
    - cat node_modules/@testing-library/jest-dom/package.json
    - ./node_modules/.bin/jest
  dependencies:
    - install_dependencies

build_project:
  stage: build
  image: node:latest
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  dependencies:
    - install_dependencies
