stages:
  - install
  - test
  - build

variables:
  KINDE_CLIENT_ID: $KINDE_CLIENT_ID
  KINDE_CLIENT_SECRET: $KINDE_CLIENT_SECRET
  KINDE_ISSUER_URL: $KINDE_ISSUER_URL
  KINDE_SITE_URL: $KINDE_SITE_URL
  KINDE_POST_LOGOUT_REDIRECT_URL: $KINDE_POST_LOGOUT_REDIRECT_URL
  KINDE_POST_LOGIN_REDIRECT_URL: $KINDE_POST_LOGIN_REDIRECT_URL

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install_dependencies:
  stage: install
  image: node:latest
  script:
    - npm install
  artifacts:
    when: always
    paths:
      - node_modules/
    expire_in: 1 week

run_tests:
  stage: test
  image: node:latest
  script:
    - pwd  # Print the current working directory
    - ls -la  # List contents of the current directory
    - ls -la node_modules/.bin/  # Verify jest is installed
    - npm test
  dependencies:
    - install_dependencies

build_project:
  stage: build
  image: node:latest
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  dependencies:
    - install_dependencies
